# Generated by Django 4.2.29 on 2026-03-13 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_share_token_alter_quizattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
